{
  "files": [
    {
      "source": "/iNaturalist/src/main/res/values/strings.xml",
      "translation": "/iNaturalist/src/main/res/values-%two_letters_code%/strings.xml",
      "dest": "/Android/strings.xml"
    }
  ],
  "project_id_env": "CROWDIN_PROJECT_ID",
  "api_token_env": "CROWDIN_PERSONAL_TOKEN",
  "preserve_hierarchy": true
}
