project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /iNaturalist/src/main/res/values/strings.xml
    dest: /Android/strings.xml
    translation: /iNaturalist/src/main/res/values-%android_code%/strings.xml
    type: android
    ignore: [
      "/google_play.xml",
      "/iOS App Store Metadata.csv",
      "/%locale%/iOS/*"
    ]
