project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
preserve_hierarchy: true

files: [
  {
    source: "/iNaturalist/src/main/res/values/strings.xml",
    translation: "/iNaturalist/src/main/res/values-%android_code%/strings.xml"
  }
]
