name: CrowdIn - Pull latest translations, verify and merge

on:
  # Allow manually triggering as well
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Once a month (first of the month), at midnight

env:
  L10N_BRANCH_NAME: l10n_main

permissions: write-all
jobs:
  crowdin-download-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%d %b %Y')" >> $GITHUB_OUTPUT

      - name: Generate pull request title
        id: pr-title
        run: echo "pr_title='Crowdin translations for ${{ steps.date.outputs.current_date }}'" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          skip_untranslated_files: true
          localization_branch_name: ${{ env.L10N_BRANCH_NAME }}
          export_only_approved: true
          create_pull_request: true
          pull_request_title: ${{ steps.pr-title.outputs.pr_title }}
          pull_request_body: ${{ steps.pr-title.outputs.pr_title }}
          commit_message: ${{ steps.pr-title.outputs.pr_title }}
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Validate & post-process
        run: python crowdin.py --delete-untranslated --crowdin-cli
        continue-on-error: false

      # - name: Add new files and commit
      #   run: |
      #     git checkout $L10N_BRANCH_NAME
      #     git status --porcelain --untracked-files iNaturalist/src/main/res/values-* | cut -c 4- | xargs git add
      #     git commit -a -m "Default & new locales for ${{ steps.date.outputs.current_date }}"
      #     git push

      - name: Add new files
        id: new-files
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Default & new locales for ${{ steps.date.outputs.current_date }}
          branch: ${{ env.L10N_BRANCH_NAME }}
          title: ${{ steps.pr-title.outputs.pr_title }}
          add-paths: |
            iNaturalist/src/main/res/values-**/strings.xml

      # - name: Find Pull Request
      #   uses: juliangruber/find-pull-request-action@v1
      #   id: find-pull-request
      #   with:
      #     branch: l10n_main

      - name: Print PR number & SHA
        env:
          number: ${{ steps.new-files.outputs.pull-request-number }}
          sha: ${{ steps.new-files.outputs.pull-request-head-sha }}
        run: echo "Pull Request ${number} (${sha})"

      # - name: Merge Pull Request
      #   uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.find-pull-request.outputs.number }}
      #     method: squash


