name: CrowdIn - Pull latest translations, verify and merge

on:
  # Allow manually triggering as well
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Once a month (first of the month), at midnight

permissions: write-all
jobs:
  crowdin-download-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%d %b %Y')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          skip_untranslated_files: true
          localization_branch_name: l10n_main
          export_only_approved: true
          create_pull_request: true
          pull_request_title: 'Crowdin translations for ${{ steps.date.outputs.current_date }}'
          pull_request_body: 'Crowdin translations for ${{ steps.date.outputs.current_date }}'
          commit_message: 'Crowdin translations for ${{ steps.date.outputs.current_date }}'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Run crowdin.py validation script
        run: python crowdin.py
        continue-on-error: false

      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: l10n_main

      - run: echo "Pull Request ${number} (${sha})"
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}

      # - name: Merge Pull Request
      #   uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.find-pull-request.outputs.number }}
      #     method: squash


